# Generated by Django 5.2.12 on 2026-03-21 01:15

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rellenar_codigos_invitacion(apps, schema_editor):
    AsignaturaGrupo = apps.get_model('evaluations', 'AsignaturaGrupo')
    for ag in AsignaturaGrupo.objects.all():
        if ag.codigo_invitacion:
            continue
        while True:
            raw = secrets.token_urlsafe(9).replace('-', 'x')[:12]
            if not AsignaturaGrupo.objects.filter(codigo_invitacion=raw).exists():
                ag.codigo_invitacion = raw
                ag.save(update_fields=['codigo_invitacion'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturagrupo',
            name='codigo_invitacion',
            field=models.CharField(blank=True, db_index=True, help_text='Código para que los alumnos se unan a la clase (se genera al guardar).', max_length=16, null=True, unique=True),
        ),
        migrations.RunPython(rellenar_codigos_invitacion, migrations.RunPython.noop),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('asignatura_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_clase', to='evaluations.asignaturagrupo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_creadas', to='evaluations.profesor')),
            ],
            options={
                'verbose_name': 'Encuesta de clase',
                'verbose_name_plural': 'Encuestas de clase',
                'ordering': ['-fecha_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la pregunta')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta de encuesta',
                'verbose_name_plural': 'Preguntas de encuesta',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveSmallIntegerField(help_text='Puntuación de 1 a 5')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_items', to='evaluations.encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluations.encuestapregunta')),
            ],
            options={
                'verbose_name': 'Respuesta (encuesta de clase)',
                'verbose_name_plural': 'Respuestas (encuestas de clase)',
            },
        ),
        migrations.CreateModel(
            name='MiembroClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('asignatura_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='evaluations.asignaturagrupo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_inscritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de clase',
                'verbose_name_plural': 'Miembros de clase',
                'constraints': [models.UniqueConstraint(fields=('user', 'asignatura_grupo'), name='unique_miembro_por_clase')],
            },
        ),
        migrations.CreateModel(
            name='ParticipacionEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='evaluations.encuesta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_encuesta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participación en encuesta',
                'verbose_name_plural': 'Participaciones en encuestas',
                'constraints': [models.UniqueConstraint(fields=('user', 'encuesta'), name='unique_participacion_encuesta')],
            },
        ),
    ]
